apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  type: ClusterIP
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
  - name: dex-grpc
    port: 5557
    protocol: TCP
    targetPort: 5557
  selector:
    app: dex
